// Puzzle actions
export const CONTINUE_PUZZLE = 'CONTINUE_PUZZLE'
export const RECEIVED_PUZZLE = 'RECEIVED_PUZZLE'
export const REQUEST_PUZZLE = 'REQUEST_PUZZLE'
export const RESET_PUZZLE = 'RESET_PUZZLE'
export const SET_TILE = 'SET_TILE'
export const UNDO_SET_TILE = 'UNDO_SET_TILE'
export const SUBMIT_PUZZLE = 'SUBMIT_PUZZLE'

// User settings actions
export const LOAD_USER_SETTINGS = 'LOAD_USER_SETTINGS'
export const RECEIVED_USER_SETTINGS = 'RECEIVED_USER_SETTINGS'
export const SET_DIFFICULTY_PREFERENCE = 'SET_DIFFICULTY_PREFERENCE'
export const SET_THEME = 'SET_THEME'
